build:
  image: docker:latest
  stage: build
  variables:
    VERSION: "0.4.0"
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull --build-arg VERSION=${VERSION} -t "$CI_REGISTRY_IMAGE" .
    - docker tag "${CI_REGISTRY_IMAGE}" "${CI_REGISTRY_IMAGE}:v${VERSION}"
    - docker push "$CI_REGISTRY_IMAGE"
    - docker push "${CI_REGISTRY_IMAGE}:v${VERSION}"
